application: gu-experiments
version: 2
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url : /related/galleries
  script: galleries.app
- url : /galleries/.*
  script: galleries.app
- url : /.*
  script: experiments.app

libraries:
- name: jinja2
  version: latest

builtins:
- remote_api: on  