application: rrees-experiments
version: 19
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /components/.*
  script: components.app
- url: /data/.*
  script: data.app
- url : /.*
  script: experiments.app

libraries:
- name: jinja2
  version: latest

builtins:
- remote_api: on  